# Generated by Django 5.0.2 on 2024-02-27 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='storeuser',
            name='store_name',
            field=models.CharField(default='', max_length=500),
        ),
    ]
