# Generated by Django 5.0.2 on 2024-02-28 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_storeuser_store_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storeuser',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
